language: python
python:
 - "2.7"
sudo: required
install: "sudo apt-get update && mysql -u root < appIV/bd.sql && python setup.py install"
#Script
script: cd appIV && pip freeze && nosetests test_sure.py